import { describe, expect, it } from 'vitest';
import ukPreset from '@/configs/uk-supplied-hs2-nte.v1.json';
import type { StarNetAdjustmentConfig, StarNetWeights } from '@/domain/entities';
import {
  buildDatPreview,
  buildSnprojPreview,
  formatDms,
  formatGons,
  type StarNetPreviewInput,
} from '@/domain/starnet/preview-builder';

const ukAdjustment: StarNetAdjustmentConfig = {
  ...(ukPreset.adjustment as Omit<StarNetAdjustmentConfig, 'defaultWeights' | 'adjustmentType' | 'linearUnits' | 'angleOutputUnits' | 'localOrGrid' | 'coordinateOrder' | 'input3dMode'>),
  adjustmentType: '3D',
  linearUnits: 'Meters',
  angleOutputUnits: 'DMS',
  localOrGrid: 'local',
  coordinateOrder: 'EN',
  input3dMode: 'Slope/Zenith',
  defaultWeights: ukPreset.adjustment.defaultWeights as StarNetWeights,
};

const frAdjustment: StarNetAdjustmentConfig = {
  ...ukAdjustment,
  angleOutputUnits: 'Gons',
  indexOfRefraction: 0.13,
  earthRadiusM: 6371000,
  maximumIterations: 30,
};

const input: StarNetPreviewInput = {
  adjustment: ukAdjustment,
  comments: ['NTE ATS34 — UK supplied dataset (demo)'],
  points: [
    { engineName: 'NTE_ATS34', eastingM: 0, northingM: 0, heightM: 0, modeE: 'fixed', modeN: 'fixed', modeH: 'fixed' },
    { engineName: 'L34RE1100_329', eastingM: 12.345, northingM: 55.12, heightM: 1.82, modeE: 'weak', modeN: 'weak', modeH: 'weak', sigmaEM: 0.001, sigmaNM: 0.001, sigmaHM: 0.001 },
    { engineName: 'PT000001', eastingM: 15.1, northingM: 42.9, heightM: 1.1, modeE: 'free', modeN: 'free', modeH: 'free' },
  ],
  blocks: [
    {
      stationEngineName: 'NTE_ATS34',
      instrumentHeightM: 0,
      rows: [
        // L-bar example: 78.4100 stored + 8.9 mm → 78.4189 final (already corrected upstream)
        { targetEngineName: 'L34RE1100_329', hzDeg: 72.40293, finalSlopeDistanceM: 78.4189, vzDeg: 90.57264, targetHeightM: 0 },
        { targetEngineName: 'PT000001', hzDeg: 10.5, finalSlopeDistanceM: 100.0, vzDeg: 89.25, targetHeightM: 0.5 },
      ],
    },
  ],
};

describe('angle formatting', () => {
  it('formats decimal degrees as STAR*NET DMS', () => {
    expect(formatDms(72.40293)).toBe('72-24-10.55');
    expect(formatDms(90)).toBe('90-00-00.00');
    expect(formatDms(89.999999)).toBe('90-00-00.00'); // rounding carry
  });

  it('formats decimal degrees as gons', () => {
    expect(formatGons(90)).toBe('100.00000');
    expect(formatGons(180)).toBe('200.00000');
  });
});

describe('.dat preview (golden, domain/23 §3–8)', () => {
  const dat = buildDatPreview(input);

  it('matches the golden UK output exactly (deterministic)', () => {
    expect(dat).toBe(`# NTE ATS34 — UK supplied dataset (demo)
# Preview generated by the BTM Topographic Adjustment mock-up — demo only, not executed
# Units: Meters, angles DMS, order EN, 3D Slope/Zenith
C  NTE_ATS34  0.0000  0.0000  0.0000  !  !  !
C  L34RE1100_329  12.3450  55.1200  1.8200  0.0010  0.0010  0.0010
C  PT000001  15.1000  42.9000  1.1000  *  *  *

DB  NTE_ATS34
DM  L34RE1100_329  72-24-10.55  78.4189  90-34-21.50  0.0000/0.0000
DM  PT000001  10-30-00.00  100.0000  89-15-00.00  0.0000/0.5000
DE
`);
  });

  it('writes pre-corrected distances and never emits .PRISM (CORR-005, domain/23 §7)', () => {
    expect(dat).toContain('78.4189'); // the corrected value, not 78.4100
    expect(dat).not.toContain('78.4100');
    expect(dat).not.toContain('.PRISM');
  });

  it('writes resolved per-sight weights for mixed reflector/EDM setups', () => {
    const weighted = buildDatPreview({
      ...input,
      blocks: [{
        ...input.blocks[0],
        rows: [{
          ...input.blocks[0].rows[1],
          sigmaHzArcSec: 2,
          sigmaVzArcSec: 3,
          sigmaSdMm: 1.5,
          sigmaSdPpm: 2,
        }],
      }],
    });
    // sqrt(1.5 mm² + (100 m × 2 ppm)²) = 0.001513 m
    expect(weighted).toContain('100.0000  89-15-00.00  2.0000  0.001513  3.0000  0.0000/0.5000');
    expect(buildSnprojPreview(ukAdjustment, 'weighted')).toContain('edm_ppm                         0.0000000000');
  });

  it('rejects a partially specified per-sight weighting model', () => {
    expect(() =>
      buildDatPreview({
        ...input,
        blocks: [{
          ...input.blocks[0],
          rows: [{ ...input.blocks[0].rows[0], sigmaHzArcSec: 2 }],
        }],
      }),
    ).toThrow(/explicit weighting requires/);
  });

  it('CORR-007: .SCALE appears only when the datum scaleFactor differs from 1 and never from T/P', () => {
    expect(dat).not.toContain('.SCALE'); // UK scaleFactor = 1.0
    const scaled = buildDatPreview({ ...input, adjustment: { ...ukAdjustment, scaleFactor: 0.99960001 } });
    expect(scaled).toContain('.SCALE 0.99960001');
    const scaledProject = buildSnprojPreview({ ...ukAdjustment, scaleFactor: 0.99960001 }, 'scaled');
    expect(scaledProject).toContain('scale_factor                    1.000000000000000');
    expect(scaledProject).not.toContain('0.99960001');
  });

  it('respects NE coordinate order when configured', () => {
    const ne = buildDatPreview({
      ...input,
      adjustment: { ...ukAdjustment, coordinateOrder: 'NE' },
      points: [
        ...input.points.slice(0, 1),
        { ...input.points[1], sigmaEM: 0.002, sigmaNM: 0.001 },
        ...input.points.slice(2),
      ],
    });
    expect(ne).toContain('C  L34RE1100_329  55.1200  12.3450  1.8200  0.0010  0.0020  0.0010');
  });

  it('formats angles in gons for the FR configuration', () => {
    const fr = buildDatPreview({ ...input, adjustment: frAdjustment });
    expect(fr).toContain('DM  PT000001  11.66667  100.0000  99.16667');
  });

  it('materialises a fixed local orientation as a synthetic fixed backsight', () => {
    const localDatum = buildDatPreview({
      ...input,
      blocks: [{ ...input.blocks[0], fixedOrientationDeg: 90 }],
    });
    expect(localDatum).toContain('C  BTMORI001  1000.0000  0.0000  0.0000  !  !  !');
    expect(localDatum).toContain('DB  NTE_ATS34\nDN  BTMORI001  0-00-00.00  !');
  });

  it('rejects a fixed orientation without a coordinate record for that station', () => {
    expect(() =>
      buildDatPreview({
        ...input,
        blocks: [{ ...input.blocks[0], stationEngineName: 'UNKNOWN', fixedOrientationDeg: 0 }],
      }),
    ).toThrow(/has no coordinate record/);
  });

  it('rejects invalid engine names instead of emitting a bad file (NAME-004/005)', () => {
    expect(() =>
      buildDatPreview({
        ...input,
        points: [{ ...input.points[0], engineName: 'BAD NAME' }],
      }),
    ).toThrow(/not a valid STAR\*NET engine name/);
  });

  it('rejects duplicate C-record engine names (POINT-015)', () => {
    expect(() => buildDatPreview({ ...input, points: [input.points[0], input.points[0]] })).toThrow(/Duplicate engine name/);
  });
});

describe('.snproj preview (golden, domain/23 §11)', () => {
  it('uses the native STAR*NET 14 project structure and exact UK supplied parameters', () => {
    const snproj = buildSnprojPreview(ukAdjustment, 'HS2_S1_NTE');
    expect(snproj).toMatch(/^\*STAR\*NET 3/);
    expect(snproj).toContain('[Adjustment]');
    expect(snproj).toContain('angle_output_units              DMS');
    expect(snproj).toContain('converge_limit                  0.0100000000');
    expect(snproj).toContain('maximum_iterations              10');
    expect(snproj).toContain('index_of_refraction             0.0700000000');
    expect(snproj).toContain('earth_radius_meters             6372000.0000000000');
    expect(snproj).toContain('chi_sqr_percent_significance    5.0000');
    expect(snproj).toContain('ell_percent_confidence          95.0000');
    expect(snproj).toContain('distance_std_err                0.0010000000');
    expect(snproj).toContain('edm_ppm                         0.0000000000');
    expect(snproj).toContain('angle_std_err                   1.4140000000');
    // ADJ-003: Auto Adjust iterations distinct from solution iterations
    expect(snproj).toContain('autoadjust_max_std_res          3.0000000000');
    expect(snproj).toContain('autoadjust_max_iterations       20');
    expect(snproj).toContain('[DataFileList]');
    expect(snproj).toContain('3 "input.dat"');
    // PROC-007: no CoMeT parameter anywhere
    expect(snproj.toLowerCase()).not.toContain('comet');
    expect(snproj.toLowerCase()).not.toContain('huber');
  });

  it('FR uses gons, 0.13 refraction, 6 371 000 m radius and 30 iterations', () => {
    const snproj = buildSnprojPreview(frAdjustment, 'FR monitoring');
    expect(snproj).toContain('angle_output_units              Gons');
    expect(snproj).toContain('index_of_refraction             0.1300000000');
    expect(snproj).toContain('earth_radius_meters             6371000.0000000000');
    expect(snproj).toContain('maximum_iterations              30');
  });

  it('rejects an unsafe data filename', () => {
    expect(() => buildSnprojPreview(ukAdjustment, 'unsafe', '..\\secret.dat')).toThrow(/Unsafe STAR\*NET data filename/);
  });
});
