import { describe, expect, it } from 'vitest';
import ukPreset from '@/configs/uk-supplied-hs2-nte.v1.json';
import type { StarNetAdjustmentConfig, StarNetWeights } from '@/domain/entities';
import {
  buildDatPreview,
  buildSnprojPreview,
  formatDms,
  formatGons,
  type StarNetPreviewInput,
} from '@/domain/starnet/preview-builder';

const ukAdjustment: StarNetAdjustmentConfig = {
  ...(ukPreset.adjustment as Omit<StarNetAdjustmentConfig, 'defaultWeights' | 'adjustmentType' | 'linearUnits' | 'angleOutputUnits' | 'localOrGrid' | 'coordinateOrder' | 'input3dMode'>),
  adjustmentType: '3D',
  linearUnits: 'Meters',
  angleOutputUnits: 'DMS',
  localOrGrid: 'local',
  coordinateOrder: 'EN',
  input3dMode: 'Slope/Zenith',
  defaultWeights: ukPreset.adjustment.defaultWeights as StarNetWeights,
};

const frAdjustment: StarNetAdjustmentConfig = {
  ...ukAdjustment,
  angleOutputUnits: 'Gons',
  indexOfRefraction: 0.13,
  earthRadiusM: 6371000,
  maximumIterations: 30,
};

const input: StarNetPreviewInput = {
  adjustment: ukAdjustment,
  comments: ['NTE ATS34 — UK supplied dataset (demo)'],
  points: [
    { engineName: 'NTE_ATS34', eastingM: 0, northingM: 0, heightM: 0, modeE: 'fixed', modeN: 'fixed', modeH: 'fixed' },
    { engineName: 'L34RE1100_329', eastingM: 12.345, northingM: 55.12, heightM: 1.82, modeE: 'weak', modeN: 'weak', modeH: 'weak', sigmaEM: 0.001, sigmaNM: 0.001, sigmaHM: 0.001 },
    { engineName: 'PT000001', eastingM: 15.1, northingM: 42.9, heightM: 1.1, modeE: 'free', modeN: 'free', modeH: 'free' },
  ],
  blocks: [
    {
      stationEngineName: 'NTE_ATS34',
      instrumentHeightM: 0,
      rows: [
        // L-bar example: 78.4100 stored + 8.9 mm → 78.4189 final (already corrected upstream)
        { targetEngineName: 'L34RE1100_329', hzDeg: 72.40293, finalSlopeDistanceM: 78.4189, vzDeg: 90.57264, targetHeightM: 0 },
        { targetEngineName: 'PT000001', hzDeg: 10.5, finalSlopeDistanceM: 100.0, vzDeg: 89.25, targetHeightM: 0.5 },
      ],
    },
  ],
};

describe('angle formatting', () => {
  it('formats decimal degrees as STAR*NET DMS', () => {
    expect(formatDms(72.40293)).toBe('72-24-10.55');
    expect(formatDms(90)).toBe('90-00-00.00');
    expect(formatDms(89.999999)).toBe('90-00-00.00'); // rounding carry
  });

  it('formats decimal degrees as gons', () => {
    expect(formatGons(90)).toBe('100.00000');
    expect(formatGons(180)).toBe('200.00000');
  });
});

describe('.dat preview (golden, domain/23 §3–8)', () => {
  const dat = buildDatPreview(input);

  it('matches the golden UK output exactly (deterministic)', () => {
    expect(dat).toBe(`# NTE ATS34 — UK supplied dataset (demo)
# Preview generated by the BTM Topographic Adjustment mock-up — demo only, not executed
# Units: Meters, angles DMS, order EN, 3D Slope/Zenith
C  NTE_ATS34  0.0000  0.0000  0.0000  !  !  !
C  L34RE1100_329  12.3450  55.1200  1.8200  0.0010  0.0010  0.0010
C  PT000001  15.1000  42.9000  1.1000  *  *  *

DB  NTE_ATS34
DM  L34RE1100_329  72-24-10.55  78.4189  90-34-21.50  0.0000/0.0000
DM  PT000001  10-30-00.00  100.0000  89-15-00.00  0.0000/0.5000
DE
`);
  });

  it('writes pre-corrected distances and never emits .PRISM (CORR-005, domain/23 §7)', () => {
    expect(dat).toContain('78.4189'); // the corrected value, not 78.4100
    expect(dat).not.toContain('78.4100');
    expect(dat).not.toContain('.PRISM');
  });

  it('CORR-007: .SCALE appears only when the datum scaleFactor differs from 1 and never from T/P', () => {
    expect(dat).not.toContain('.SCALE'); // UK scaleFactor = 1.0
    const scaled = buildDatPreview({ ...input, adjustment: { ...ukAdjustment, scaleFactor: 0.99960001 } });
    expect(scaled).toContain('.SCALE 0.99960001');
  });

  it('respects NE coordinate order when configured', () => {
    const ne = buildDatPreview({ ...input, adjustment: { ...ukAdjustment, coordinateOrder: 'NE' } });
    expect(ne).toContain('C  L34RE1100_329  55.1200  12.3450  1.8200');
  });

  it('formats angles in gons for the FR configuration', () => {
    const fr = buildDatPreview({ ...input, adjustment: frAdjustment });
    expect(fr).toContain('DM  PT000001  11.66667  100.0000  99.16667');
  });

  it('rejects invalid engine names instead of emitting a bad file (NAME-004/005)', () => {
    expect(() =>
      buildDatPreview({
        ...input,
        points: [{ ...input.points[0], engineName: 'BAD NAME' }],
      }),
    ).toThrow(/not a valid STAR\*NET engine name/);
  });

  it('rejects duplicate C-record engine names (POINT-015)', () => {
    expect(() => buildDatPreview({ ...input, points: [input.points[0], input.points[0]] })).toThrow(/Duplicate engine name/);
  });
});

describe('.snproj preview (golden, domain/23 §11)', () => {
  it('carries the exact UK supplied parameters (32 §8 P0)', () => {
    const snproj = buildSnprojPreview(ukAdjustment, 'HS2_S1_NTE');
    expect(snproj).toContain('AngleUnits=DMS');
    expect(snproj).toContain('ConvergeLimit=0.01');
    expect(snproj).toContain('MaxIterations=10');
    expect(snproj).toContain('IndexOfRefraction=0.07');
    expect(snproj).toContain('EarthRadius=6372000');
    expect(snproj).toContain('ChiSquareSignificance=5');
    expect(snproj).toContain('EllipseConfidence=95');
    expect(snproj).toContain('DistanceStdErr=0.001');
    expect(snproj).toContain('DistancePPM=1');
    expect(snproj).toContain('AngleStdErrSec=1.414');
    // ADJ-003: Auto Adjust iterations distinct from solution iterations
    expect(snproj).toContain('MaxStandardizedResidual=3');
    expect(snproj.match(/MaxIterations=10/g)).toHaveLength(1);
    expect(snproj.match(/MaxIterations=20/g)).toHaveLength(1);
    // PROC-007: no CoMeT parameter anywhere
    expect(snproj.toLowerCase()).not.toContain('comet');
    expect(snproj.toLowerCase()).not.toContain('huber');
  });

  it('FR uses gons, 0.13 refraction, 6 371 000 m radius and 30 iterations', () => {
    const snproj = buildSnprojPreview(frAdjustment, 'FR monitoring');
    expect(snproj).toContain('AngleUnits=Gons');
    expect(snproj).toContain('IndexOfRefraction=0.13');
    expect(snproj).toContain('EarthRadius=6371000');
    expect(snproj).toContain('MaxIterations=30');
  });
});
