import type { ConstraintMode, StarNetAdjustmentConfig } from '@/domain/entities';
import { isValidEngineName } from '@/domain/point-identity/engine-names';

/**
 * STAR*NET `.dat`/`.snproj` PREVIEW builder (`domain/23-STARNET-IO-ET-CORRECTIONS.md`).
 * Pure, in-memory, deterministic. The mock-up only previews these files — STAR*NET is never
 * executed here, and no filesystem access exists in this module. In production the Windows
 * service generates real files per run into an isolated workspace (VER-005..007).
 *
 * Canonical choices (domain/23 §6–8):
 * - slope distances are written ALREADY corrected (prism delta + atmospheric ppm applied by the
 *   corrections module); `.PRISM` is NOT emitted, avoiding any double treatment (CORR-005);
 * - `.SCALE` comes exclusively from the datum `scaleFactor` of the adjustment config and is
 *   never derived from T/P (CORR-007);
 * - point/station names are engine names validated by NAME-004/005; an invalid name aborts the
 *   preview rather than silently emitting a bad file.
 */

export interface DatPoint {
  engineName: string;
  eastingM: number;
  northingM: number;
  heightM: number;
  modeE: ConstraintMode;
  modeN: ConstraintMode;
  modeH: ConstraintMode;
  sigmaEM?: number;
  sigmaNM?: number;
  sigmaHM?: number;
}

export interface DatObservationRow {
  targetEngineName: string;
  hzDeg: number;
  /** FINAL corrected slope distance (output of applyDistanceCorrections). */
  finalSlopeDistanceM: number;
  vzDeg: number;
  targetHeightM: number;
  sigmaHzArcSec?: number;
  sigmaVzArcSec?: number;
  sigmaSdMm?: number;
  sigmaSdPpm?: number;
}

export interface DatStationBlock {
  stationEngineName: string;
  instrumentHeightM: number;
  /**
   * Fixed local-datum orientation, clockwise from North. When present the builder creates one
   * synthetic fixed backsight and a fixed DN reading; this is equivalent to fixing the station
   * orientation without pretending the auxiliary point is a BTM target.
   */
  fixedOrientationDeg?: number;
  rows: DatObservationRow[];
}

export interface StarNetPreviewInput {
  adjustment: StarNetAdjustmentConfig;
  points: DatPoint[];
  blocks: DatStationBlock[];
  /** Comment header lines (job name, slot, provenance). Never data. */
  comments?: string[];
}

export class StarNetPreviewError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StarNetPreviewError';
  }
}

function num(value: number, decimals: number): string {
  return value.toFixed(decimals);
}

/** Decimal degrees -> STAR*NET DMS angle string `dd-mm-ss.ss`. */
export function formatDms(deg: number): string {
  const sign = deg < 0 ? '-' : '';
  let abs = Math.abs(deg);
  let d = Math.floor(abs);
  let m = Math.floor((abs - d) * 60);
  let s = ((abs - d) * 60 - m) * 60;
  // carry rounding (e.g. 59.995s -> next minute)
  if (Number(s.toFixed(2)) >= 60) {
    s = 0;
    m += 1;
  }
  if (m >= 60) {
    m = 0;
    d += 1;
  }
  return `${sign}${d}-${String(m).padStart(2, '0')}-${s.toFixed(2).padStart(5, '0')}`;
}

/** Decimal degrees -> gons (grads), 5 decimals. */
export function formatGons(deg: number): string {
  return num((deg * 400) / 360, 5);
}

function formatAngle(deg: number, units: StarNetAdjustmentConfig['angleOutputUnits']): string {
  return units === 'DMS' ? formatDms(deg) : formatGons(deg);
}

function constraintToken(mode: ConstraintMode, sigmaM: number | undefined, pointName: string, component: string): string {
  switch (mode) {
    case 'fixed':
      return '!';
    case 'free':
      return '*';
    case 'weak': {
      if (sigmaM === undefined || !(sigmaM > 0)) {
        throw new StarNetPreviewError(`Point ${pointName}: weak ${component} constraint requires a positive sigma`);
      }
      return num(sigmaM, 4);
    }
  }
}

function assertEngineName(name: string, what: string): void {
  if (!isValidEngineName(name)) {
    throw new StarNetPreviewError(`${what} "${name}" is not a valid STAR*NET engine name (NAME-004/005)`);
  }
}

/** Builds the `.dat` preview text (domain/23 §3–6). */
export function buildDatPreview(input: StarNetPreviewInput): string {
  const { adjustment, points, blocks } = input;
  const lines: string[] = [];
  for (const comment of input.comments ?? []) lines.push(`# ${comment}`);
  lines.push(`# Preview generated by the BTM Topographic Adjustment mock-up — demo only, not executed`);
  lines.push(`# Units: Meters, angles ${adjustment.angleOutputUnits}, order ${adjustment.coordinateOrder}, 3D ${adjustment.input3dMode}`);

  // .SCALE strictly from the datum configuration (CORR-007) — omitted at the neutral value.
  if (adjustment.scaleFactor !== 1) {
    lines.push(`.SCALE ${num(adjustment.scaleFactor, 8)}`);
  }

  const seen = new Set<string>();
  const pointByName = new Map(points.map((point) => [point.engineName, point]));
  for (const point of points) {
    assertEngineName(point.engineName, 'Point');
    if (seen.has(point.engineName)) {
      throw new StarNetPreviewError(`Duplicate engine name "${point.engineName}" in C records (NAME-006/POINT-015)`);
    }
    seen.add(point.engineName);
    const first = adjustment.coordinateOrder === 'EN' ? point.eastingM : point.northingM;
    const second = adjustment.coordinateOrder === 'EN' ? point.northingM : point.eastingM;
    const firstMode = adjustment.coordinateOrder === 'EN' ? point.modeE : point.modeN;
    const secondMode = adjustment.coordinateOrder === 'EN' ? point.modeN : point.modeE;
    const firstSigma = adjustment.coordinateOrder === 'EN' ? point.sigmaEM : point.sigmaNM;
    const secondSigma = adjustment.coordinateOrder === 'EN' ? point.sigmaNM : point.sigmaEM;
    const firstComponent = adjustment.coordinateOrder === 'EN' ? 'E' : 'N';
    const secondComponent = adjustment.coordinateOrder === 'EN' ? 'N' : 'E';
    const tokens = [
      'C',
      point.engineName,
      num(first, 4),
      num(second, 4),
      num(point.heightM, 4),
      constraintToken(firstMode, firstSigma, point.engineName, firstComponent),
      constraintToken(secondMode, secondSigma, point.engineName, secondComponent),
      constraintToken(point.modeH, point.sigmaHM, point.engineName, 'H'),
    ];
    lines.push(tokens.join('  '));
  }

  const fixedOrientationBacksights = new Map<string, string>();
  for (const [blockIndex, block] of blocks.entries()) {
    if (block.fixedOrientationDeg === undefined) continue;
    const station = pointByName.get(block.stationEngineName);
    if (!station) {
      throw new StarNetPreviewError(`Fixed orientation station "${block.stationEngineName}" has no coordinate record`);
    }
    let suffix = blockIndex + 1;
    let backsightName = `BTMORI${String(suffix).padStart(3, '0')}`;
    while (seen.has(backsightName)) {
      suffix += 1;
      backsightName = `BTMORI${String(suffix).padStart(3, '0')}`;
    }
    seen.add(backsightName);
    fixedOrientationBacksights.set(block.stationEngineName, backsightName);
    const orientationRad = (block.fixedOrientationDeg * Math.PI) / 180;
    const eastingM = station.eastingM + 1000 * Math.sin(orientationRad);
    const northingM = station.northingM + 1000 * Math.cos(orientationRad);
    const first = adjustment.coordinateOrder === 'EN' ? eastingM : northingM;
    const second = adjustment.coordinateOrder === 'EN' ? northingM : eastingM;
    lines.push(
      ['C', backsightName, num(first, 4), num(second, 4), num(station.heightM, 4), '!', '!', '!'].join('  '),
    );
  }

  for (const block of blocks) {
    assertEngineName(block.stationEngineName, 'Station');
    lines.push('');
    lines.push(`DB  ${block.stationEngineName}`);
    const fixedBacksight = fixedOrientationBacksights.get(block.stationEngineName);
    if (fixedBacksight) {
      lines.push(['DN', fixedBacksight, formatAngle(0, adjustment.angleOutputUnits), '!'].join('  '));
    }
    for (const row of block.rows) {
      assertEngineName(row.targetEngineName, 'Target');
      const explicitWeightValues = [row.sigmaHzArcSec, row.sigmaVzArcSec, row.sigmaSdMm, row.sigmaSdPpm];
      const hasAnyExplicitWeight = explicitWeightValues.some((value) => value !== undefined);
      if (hasAnyExplicitWeight && explicitWeightValues.some((value) => value === undefined)) {
        throw new StarNetPreviewError(`Target ${row.targetEngineName}: explicit weighting requires Hz, Vz, distance mm and ppm`);
      }
      const standardErrors = hasAnyExplicitWeight
        ? [
            num(row.sigmaHzArcSec!, 4),
            num(
              Math.hypot(
                row.sigmaSdMm! / 1000,
                row.finalSlopeDistanceM * row.sigmaSdPpm! * 1e-6,
              ),
              6,
            ),
            num(row.sigmaVzArcSec!, 4),
          ]
        : [];
      // DM  TARGET  HZ  SLOPE_DISTANCE  ZENITH  HI/HT (domain/23 §4–5: both heights, never a delta)
      lines.push(
        [
          'DM',
          row.targetEngineName,
          formatAngle(row.hzDeg, adjustment.angleOutputUnits),
          num(row.finalSlopeDistanceM, 4),
          formatAngle(row.vzDeg, adjustment.angleOutputUnits),
          ...standardErrors,
          `${num(block.instrumentHeightM, 4)}/${num(row.targetHeightM, 4)}`,
        ].join('  '),
      );
    }
    lines.push('DE');
  }

  return `${lines.join('\n')}\n`;
}

function nativeProjectLine(key: string, value: string | number): string {
  return `${key.padEnd(32, ' ')}${value}`;
}

function safeProjectComment(value: string): string {
  return value.replace(/[\r\n#]/g, ' ').trim().slice(0, 120);
}

/**
 * Builds a native STAR*NET 14 `.snproj`.
 *
 * The previous mock-up emitted a conceptual INI preview whose key names were not accepted by
 * STAR*NET. This builder follows the supplied STAR*NET 14 `*STAR*NET 3` project structure and
 * native lower-case keys. Plot/UI-only sections are deliberately omitted. The Windows bridge
 * still treats this as generated, disposable input and STAR*NET remains the authority.
 */
export function buildSnprojPreview(
  adjustment: StarNetAdjustmentConfig,
  jobName: string,
  dataFileName = 'input.dat',
): string {
  if (!/^[A-Za-z0-9_.-]+\.dat$/i.test(dataFileName)) {
    throw new StarNetPreviewError(`Unsafe STAR*NET data filename "${dataFileName}"`);
  }
  const w = adjustment.defaultWeights;
  if (!w) {
    throw new StarNetPreviewError('STAR*NET instrument weights must be resolved before generating a native project');
  }
  const lines = [
    '*STAR*NET 3',
    '#',
    '# 14.0',
    `# Generated by BTM mock-up bridge: ${safeProjectComment(jobName)}`,
    '#',
    '',
    '[Adjustment]',
    '#',
    nativeProjectLine('adjustment_type', adjustment.adjustmentType),
    nativeProjectLine('linear_units', adjustment.linearUnits),
    nativeProjectLine('angle_output_units', adjustment.angleOutputUnits),
    nativeProjectLine('local_or_grid_adjustment', adjustment.localOrGrid === 'local' ? 0 : 1),
    nativeProjectLine('coordinate_projection', 0),
    nativeProjectLine('coordinate_zone', 0),
    nativeProjectLine('coordinate_system_use_wgs84', 'N'),
    nativeProjectLine('utm_hemisphere', 'N'),
    nativeProjectLine('project_elevation', '0.000000000000000'),
    nativeProjectLine('local_default_datum', 1),
    nativeProjectLine('common_datum_reduction', '0.0000000000'),
    // The resolved datum/grid factor is emitted once as `.SCALE` in input.dat. Keep the project
    // default neutral, matching the supplied UK project, to make double application impossible.
    nativeProjectLine('scale_factor', '1.000000000000000'),
    nativeProjectLine('geoid_height', '0.000000'),
    nativeProjectLine('vert_defl_north', '0.000000'),
    nativeProjectLine('vert_defl_east', '0.000000'),
    nativeProjectLine('coordinate_order', adjustment.coordinateOrder),
    nativeProjectLine('coordinate_order_north', 'N'),
    nativeProjectLine('angle_station_order', 'At-From-To'),
    nativeProjectLine('3D_input_mode', adjustment.input3dMode),
    nativeProjectLine('index_of_refraction', adjustment.indexOfRefraction.toFixed(10)),
    nativeProjectLine('earth_radius_meters', adjustment.earthRadiusM.toFixed(10)),
    nativeProjectLine('converge_limit', adjustment.convergeLimit.toFixed(10)),
    nativeProjectLine('maximum_iterations', adjustment.maximumIterations),
    nativeProjectLine('chi_sqr_percent_significance', adjustment.chiSquareSignificancePercent.toFixed(4)),
    nativeProjectLine('fixed_linear_std_err', '1.000000000000000e-07'),
    nativeProjectLine('fixed_angular_std_err', '1.000100000000000e-03'),
    nativeProjectLine('perform_error_propagation', adjustment.performErrorPropagation ? 1 : 0),
    nativeProjectLine('ell_percent_confidence', adjustment.ellipseConfidencePercent.toFixed(4)),
    '',
    '[Listing]',
    '#',
    nativeProjectLine('print_input_file', 0),
    nativeProjectLine('list_observations', 1),
    nativeProjectLine('list_sideshot_observations', 1),
    nativeProjectLine('list_adj_obs_residuals', 1),
    nativeProjectLine('list_adj_dist_az', 1),
    nativeProjectLine('list_converge', 1),
    nativeProjectLine('list_traverses', 1),
    nativeProjectLine('list_coordinates', 1),
    nativeProjectLine('list_positions', 1),
    nativeProjectLine('list_sideshot_coordinates', 1),
    nativeProjectLine('list_file_references', 1),
    nativeProjectLine('list_standard_deviations', 1),
    nativeProjectLine('list_station_ellipses', 1),
    nativeProjectLine('list_relative_ellipses', 1),
    nativeProjectLine('create_coordinate_file', 1),
    nativeProjectLine('coordinate_output_script', 'Default'),
    nativeProjectLine('number_coord_decimals', 5),
    nativeProjectLine('number_elevation_decimals', 5),
    nativeProjectLine('autoadjust_max_std_res', adjustment.autoAdjust.maxStandardizedResidual.toFixed(10)),
    nativeProjectLine('autoadjust_outliers_removed', adjustment.autoAdjust.outliersRemovedPerIteration),
    nativeProjectLine('autoadjust_max_iterations', adjustment.autoAdjust.maxIterations),
    '',
    '[Instrument]',
    '#',
    nativeProjectLine('distance_std_err', w.distanceStdErrM.toFixed(10)),
    // Distance mm+ppm is resolved per sight and emitted as an explicit DM standard error.
    nativeProjectLine('edm_ppm', '0.0000000000'),
    nativeProjectLine('angle_std_err', w.angleArcSec.toFixed(10)),
    nativeProjectLine('direction_std_err', w.directionArcSec.toFixed(10)),
    nativeProjectLine('azimuth_std_err', w.azimuthArcSec.toFixed(10)),
    nativeProjectLine('zenith_std_err', w.zenithArcSec.toFixed(10)),
    nativeProjectLine('delta_elev_std_err', '0.0152400000'),
    nativeProjectLine('delta_elev_ppm', '1.0000000000'),
    nativeProjectLine('instrument_centering_error', w.instrumentCenteringM.toFixed(10)),
    nativeProjectLine('target_centering_error', w.targetCenteringM.toFixed(10)),
    nativeProjectLine('vertical_centering_error', w.verticalCenteringM.toFixed(10)),
    nativeProjectLine('level_section_type', 'LENGTH'),
    nativeProjectLine('level_std_err', '0.000047434164903'),
    '',
    '[DataFileList]',
    '#',
    `3 "${dataFileName}"`,
    '##################################################',
  ];
  return `${lines.join('\n')}\n`;
}
