import type { ConstraintMode, StarNetAdjustmentConfig } from '@/domain/entities';
import { isValidEngineName } from '@/domain/point-identity/engine-names';

/**
 * STAR*NET `.dat`/`.snproj` PREVIEW builder (`domain/23-STARNET-IO-ET-CORRECTIONS.md`).
 * Pure, in-memory, deterministic. The mock-up only previews these files — STAR*NET is never
 * executed here, and no filesystem access exists in this module. In production the Windows
 * service generates real files per run into an isolated workspace (VER-005..007).
 *
 * Canonical choices (domain/23 §6–8):
 * - slope distances are written ALREADY corrected (prism delta + atmospheric ppm applied by the
 *   corrections module); `.PRISM` is NOT emitted, avoiding any double treatment (CORR-005);
 * - `.SCALE` comes exclusively from the datum `scaleFactor` of the adjustment config and is
 *   never derived from T/P (CORR-007);
 * - point/station names are engine names validated by NAME-004/005; an invalid name aborts the
 *   preview rather than silently emitting a bad file.
 */

export interface DatPoint {
  engineName: string;
  eastingM: number;
  northingM: number;
  heightM: number;
  modeE: ConstraintMode;
  modeN: ConstraintMode;
  modeH: ConstraintMode;
  sigmaEM?: number;
  sigmaNM?: number;
  sigmaHM?: number;
}

export interface DatObservationRow {
  targetEngineName: string;
  hzDeg: number;
  /** FINAL corrected slope distance (output of applyDistanceCorrections). */
  finalSlopeDistanceM: number;
  vzDeg: number;
  targetHeightM: number;
}

export interface DatStationBlock {
  stationEngineName: string;
  instrumentHeightM: number;
  rows: DatObservationRow[];
}

export interface StarNetPreviewInput {
  adjustment: StarNetAdjustmentConfig;
  points: DatPoint[];
  blocks: DatStationBlock[];
  /** Comment header lines (job name, slot, provenance). Never data. */
  comments?: string[];
}

export class StarNetPreviewError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'StarNetPreviewError';
  }
}

function num(value: number, decimals: number): string {
  return value.toFixed(decimals);
}

/** Decimal degrees -> STAR*NET DMS angle string `dd-mm-ss.ss`. */
export function formatDms(deg: number): string {
  const sign = deg < 0 ? '-' : '';
  let abs = Math.abs(deg);
  let d = Math.floor(abs);
  let m = Math.floor((abs - d) * 60);
  let s = ((abs - d) * 60 - m) * 60;
  // carry rounding (e.g. 59.995s -> next minute)
  if (Number(s.toFixed(2)) >= 60) {
    s = 0;
    m += 1;
  }
  if (m >= 60) {
    m = 0;
    d += 1;
  }
  return `${sign}${d}-${String(m).padStart(2, '0')}-${s.toFixed(2).padStart(5, '0')}`;
}

/** Decimal degrees -> gons (grads), 5 decimals. */
export function formatGons(deg: number): string {
  return num((deg * 400) / 360, 5);
}

function formatAngle(deg: number, units: StarNetAdjustmentConfig['angleOutputUnits']): string {
  return units === 'DMS' ? formatDms(deg) : formatGons(deg);
}

function constraintToken(mode: ConstraintMode, sigmaM: number | undefined, pointName: string, component: string): string {
  switch (mode) {
    case 'fixed':
      return '!';
    case 'free':
      return '*';
    case 'weak': {
      if (sigmaM === undefined || !(sigmaM > 0)) {
        throw new StarNetPreviewError(`Point ${pointName}: weak ${component} constraint requires a positive sigma`);
      }
      return num(sigmaM, 4);
    }
  }
}

function assertEngineName(name: string, what: string): void {
  if (!isValidEngineName(name)) {
    throw new StarNetPreviewError(`${what} "${name}" is not a valid STAR*NET engine name (NAME-004/005)`);
  }
}

/** Builds the `.dat` preview text (domain/23 §3–6). */
export function buildDatPreview(input: StarNetPreviewInput): string {
  const { adjustment, points, blocks } = input;
  const lines: string[] = [];
  for (const comment of input.comments ?? []) lines.push(`# ${comment}`);
  lines.push(`# Preview generated by the BTM Topographic Adjustment mock-up — demo only, not executed`);
  lines.push(`# Units: Meters, angles ${adjustment.angleOutputUnits}, order ${adjustment.coordinateOrder}, 3D ${adjustment.input3dMode}`);

  // .SCALE strictly from the datum configuration (CORR-007) — omitted at the neutral value.
  if (adjustment.scaleFactor !== 1) {
    lines.push(`.SCALE ${num(adjustment.scaleFactor, 8)}`);
  }

  const seen = new Set<string>();
  for (const point of points) {
    assertEngineName(point.engineName, 'Point');
    if (seen.has(point.engineName)) {
      throw new StarNetPreviewError(`Duplicate engine name "${point.engineName}" in C records (NAME-006/POINT-015)`);
    }
    seen.add(point.engineName);
    const first = adjustment.coordinateOrder === 'EN' ? point.eastingM : point.northingM;
    const second = adjustment.coordinateOrder === 'EN' ? point.northingM : point.eastingM;
    const tokens = [
      'C',
      point.engineName,
      num(first, 4),
      num(second, 4),
      num(point.heightM, 4),
      constraintToken(point.modeE, point.sigmaEM, point.engineName, 'E'),
      constraintToken(point.modeN, point.sigmaNM, point.engineName, 'N'),
      constraintToken(point.modeH, point.sigmaHM, point.engineName, 'H'),
    ];
    lines.push(tokens.join('  '));
  }

  for (const block of blocks) {
    assertEngineName(block.stationEngineName, 'Station');
    lines.push('');
    lines.push(`DB  ${block.stationEngineName}`);
    for (const row of block.rows) {
      assertEngineName(row.targetEngineName, 'Target');
      // DM  TARGET  HZ  SLOPE_DISTANCE  ZENITH  HI/HT (domain/23 §4–5: both heights, never a delta)
      lines.push(
        [
          'DM',
          row.targetEngineName,
          formatAngle(row.hzDeg, adjustment.angleOutputUnits),
          num(row.finalSlopeDistanceM, 4),
          formatAngle(row.vzDeg, adjustment.angleOutputUnits),
          `${num(block.instrumentHeightM, 4)}/${num(row.targetHeightM, 4)}`,
        ].join('  '),
      );
    }
    lines.push('DE');
  }

  return `${lines.join('\n')}\n`;
}

/** Builds the `.snproj` preview text — minimum Adjustment/Instrument sections (domain/23 §11). */
export function buildSnprojPreview(adjustment: StarNetAdjustmentConfig, jobName: string): string {
  const w = adjustment.defaultWeights;
  const lines = [
    `# ${jobName} — .snproj preview (BTM mock-up, demo only)`,
    '[Project]',
    `AdjustmentType=${adjustment.adjustmentType}`,
    `LinearUnits=${adjustment.linearUnits}`,
    `AngleUnits=${adjustment.angleOutputUnits}`,
    `CoordinateSystem=${adjustment.localOrGrid === 'local' ? 'Local' : 'Grid'}`,
    `CoordinateOrder=${adjustment.coordinateOrder}`,
    `Input3DMode=${adjustment.input3dMode}`,
    '',
    '[Adjustment]',
    `ConvergeLimit=${adjustment.convergeLimit}`, // unitless (ADJ-002)
    `MaxIterations=${adjustment.maximumIterations}`,
    `ChiSquareSignificance=${adjustment.chiSquareSignificancePercent}`,
    `ErrorPropagation=${adjustment.performErrorPropagation ? 'On' : 'Off'}`,
    `EllipseConfidence=${adjustment.ellipseConfidencePercent}`,
    `ScaleFactor=${adjustment.scaleFactor}`,
    `IndexOfRefraction=${adjustment.indexOfRefraction}`,
    `EarthRadius=${adjustment.earthRadiusM}`,
    '',
    '[Instrument]',
    `DistanceStdErr=${w.distanceStdErrM}`, // metres in .snproj (domain/23 §10)
    `DistancePPM=${w.distancePpm}`,
    `AngleStdErrSec=${w.angleArcSec}`,
    `DirectionStdErrSec=${w.directionArcSec}`,
    `AzimuthStdErrSec=${w.azimuthArcSec}`,
    `ZenithStdErrSec=${w.zenithArcSec}`,
    `InstrumentCentering=${w.instrumentCenteringM}`,
    `TargetCentering=${w.targetCenteringM}`,
    `VerticalCentering=${w.verticalCenteringM}`,
    '',
    '[AutoAdjust]',
    `Enabled=${adjustment.autoAdjust.enabled ? 'On' : 'Off'}`,
    `MaxStandardizedResidual=${adjustment.autoAdjust.maxStandardizedResidual}`,
    `OutliersRemovedPerIteration=${adjustment.autoAdjust.outliersRemovedPerIteration}`,
    `MaxIterations=${adjustment.autoAdjust.maxIterations}`, // distinct from solution iterations (ADJ-003)
  ];
  return `${lines.join('\n')}\n`;
}
